name: Publish Docker Image

on:
  release:
    types: [published]
  # Could run this on any tag being pushed matching a glob patter.
  # push:
  #   tags:
  #     - 'v*.*.*'

env:
  APPFOLDER: tunafish
  DOCKERHUB_NAMESPACE: johnunderwood197
  DOCKERHUB_REPO: tunafish

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_REPO }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./${{ env.APPFOLDER }}
          file: ./${{ env.APPFOLDER }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # tags: ${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
